name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json      
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}  
      
      - name: Build solution and generate NuGet package
        run: |  
          cd StreamChats/
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry
        run: |
          cd StreamChats/out/
          dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_KEY}}
